// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shikService.Infrastructure.Ef;

namespace shikService.Infrastructure.Migrations
{
    [DbContext(typeof(shikServiceDbContext))]
    [Migration("20190902150137_owned-type")]
    partial class ownedtype
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("shikService.Infrastructure.Model.userEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Pw");

                    b.HasKey("Id");

                    b.ToTable("userEntitys");
                });

            modelBuilder.Entity("shikService.Infrastructure.Model.userEntity", b =>
                {
                    b.OwnsOne("shikService.Infrastructure.Model.userDetailEntity", "Detail", b1 =>
                        {
                            b1.Property<string>("userEntityId");

                            b1.Property<string>("Address");

                            b1.Property<string>("Name");

                            b1.ToTable("userEntitys");

                            b1.HasOne("shikService.Infrastructure.Model.userEntity")
                                .WithOne("Detail")
                                .HasForeignKey("shikService.Infrastructure.Model.userDetailEntity", "userEntityId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
